version: '3.8'

services:
  backend:
    build: .
    container_name: nestjs_app
    depends_on:
      - database
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DATABASE_TYPE: postgres
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: postgres
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    restart: unless-stopped

  database:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      #- ./db.sql:/docker-entrypoint-initdb.d/db.sql

volumes:
  pgdata: